Cria estrutura básica do pacote `dpm-r`.
splor-mg/dpm-r pull request #3
Opened 2024-05-16 19:51 UTC by hslinhares

Closes #1 

@fjuniorr utilizei os pacotes `usethis` e `roxygen2` para criação da estrutura básica do pacote.

2024-05-17 14:19 UTC, fjuniorr requested changes
@hslinhares apesar do nome do repositório ser `dpm-r` para o nome do pacote podemos usar simplesmente `dpm`. O sufixo é para distinguirmos o repositório do `dpm` em python, mas no nome do pacote isso não é uma questão.

Estou seguindo a inspiração da frictionless para isso:

- https://github.com/frictionlessdata/frictionless-py
- https://github.com/frictionlessdata/frictionless-r
- https://github.com/frictionlessdata/frictionless-js

Sobre o pacote em si, você testou a execução da função? Eu recebo

```R
dp <- read_datapackage("https://raw.githubusercontent.com/splor-mg/dados-totais-armazem-siafi/main/datapackage.json")
Error in is_url(path) : could not find function "is_url"
```

A função `is_url` é uma dependência que você não trouxe para esse pacote. Por fim, fica atento que todos os pacotes usados devem ser listados no campo `Imports` do arquivo `DESCRIPTION`.

2024-05-20 14:03 UTC, hslinhares commented
> A função `is_url` é uma dependência que você não trouxe para esse pacote. Por fim, fica atento que todos os pacotes usados devem ser listados no campo `Imports` do arquivo `DESCRIPTION`.

Me atentei ao arquivo `DESCRIPTION` do `checks-planejamento`, e lá não constava a função `is_url`. Ela está no [utils.R](https://github.com/splor-mg/checks-planejamento/blob/main/R/utils.R). Passou despercebido por mim se tratar de uma função.

2024-05-20 14:23 UTC, hslinhares commented
@fjuniorr 

- fiz a alteração do nome do pacote para `dpm`. 

- Em relação ao nome do branch, resolvi não mudar agora porque retornou mensagem alertando que eu perderia o `pull request` aberto. Para os próximos, estou atento quanto a manter em caixa baixa.

- Nos campos de `Authors@R:` do https://github.com/splor-mg/dpm-r/blob/CreatingPackage/DESCRIPTION, vou manter os seus dados conforme em https://github.com/splor-mg/checks-planejamento/blob/main/DESCRIPTION, porque você quem idealizou o pacote, ok?

2024-05-21 13:51 UTC, fjuniorr approved these changes
> Nos campos de Authors@R: do https://github.com/splor-mg/dpm-r/blob/CreatingPackage/DESCRIPTION, vou manter os seus dados conforme em https://github.com/splor-mg/checks-planejamento/blob/main/DESCRIPTION, porque você quem idealizou o pacote, ok?

Pode colocar eu e você como autores.

No mais fiz algumas alterações diretamente. Dá uma olhada e depois de alterar os autores pode fazer um squash merge.

2024-05-22 15:34 UTC, merged